from GraphicEngine import *


vector_1 = Vector([1, 2, 3])
vector_2 = Vector([1.8, 2.1, 4.5])

point_1 = Point([1, 2, 3])
point_2 = Point([1, 5, 8])

matrix_1 = Matrix([[2.0, 3.0], [5.1, 3.8], [8.5, 8.0]])
matrix_2 = Matrix([[1.0, 2.0, 1.0], [4.1, 2.8, 1.0]])
matrix_3 = Matrix([[1, 2, 3], [4, 5, 6], [9, 8, 8]])
matrix_4 = Matrix([[2, 3, 4], [1, 2, 3], [2, 2, 8]])
matrix_0 = Matrix([[1.0, 2.0], [3, 4]])

Vector_Space = VectorSpace([Vector([1, 0, 0]), Vector([0, 1, 0]), Vector([0, 0, 1])])



print("...............МАТРИЦЫ...............")
print("sum of two matrices")
print(matrix_3 + matrix_3)
print("difference of two matrices")
print(matrix_4 - matrix_3)
print("the product of a matrix and a scalar")
print(matrix_1 * (1/5))
print("the product of a scalar and a matrix")
print(5 * matrix_1)
print("transpose matrix")
print(matrix_1.transpose())
print("the product of matrices")
print(matrix_1 * matrix_2)
print("the product of matrices")
print(matrix_2 * matrix_1)
print("matrix determinant")
print(matrix_3.determinant())
print("identity matrix")
print(Matrix.identity(5))
print("inverse matrix")
print(~matrix_3)
print("gram matrix")
print(matrix_0.gram_matrix())
print("\n")

print("...............ВЕКТОРЫ...............")
print("vector: ")
print(vector_1)
print("sum of two vectors: ")
print(vector_1 + vector_2)
print("difference of two vectors: ")
print(vector_1 - vector_2)
print("vector * number: ")
print(vector_1 * 5)
print("number * vector: ")
print(5 * vector_1)
print("scalar product of vectors: ")
print(vector_1 % vector_2)
print("vector product of vectors: ")
print(vector_2 ** vector_1)
print("transpose vector")
print(vector_1.transpose())
print("length of vector")
print(Vector.length(vector_1))
print("\n")
print(vector_1.identity())

print(".............BilinearForm.............")
print(BilinearForm(matrix_3, vector_1, vector_2))
print("\n")

print("................ТОЧКИ................")
print("point + vector: ")
print(point_1 + vector_1)
print("vector + point: ")
print(vector_1 + point_1)
print("difference of two points: ")
print(point_1 - point_2)
print("\n")

print("........Векторное пространство........")
print(Vector_Space.scalar_product(vector_1, vector_2))
print(Vector_Space.as_vector(point_1))